### ISSUE TITLE
I don't think the status-code is checked

### ISSUE THREAD

**Issue by paul-hammant** [TodoBackend/todo-backend-js-spec#11]
If an implementation responds with 200 for everything, the suite still passes. I don't think it should be so forgiving.

**Comment by moredip** [comment]
Changing this would be a breaking change to the spec, in that implementations which had previously passed would start failing. 

While I can see the argument that it would be better to specify expected status codes, it would have to be tackled as part of some sort of new major version of the spec (in [semver](https://semver.org/) terms).

**Comment by paul-hammant** [comment]
Makes sense. I can do the work in the Sv port as were divergent anyway.

**Comment by paul-hammant** [comment]
Coded it in our fork - https://github.com/servirtium/compatibility-suite/commit/2f1836c16580e80c01fa683062d06f9196458341 :)
