### ISSUE TITLE
Error: global leaks detected

### ISSUE THREAD

**Issue by tuupola** [TodoBackend/todo-backend-js-spec#3]
Currently the first test in specs fail with: _Error: global leaks detected: _eid_promises, TokenSigning_. For example [Sinatra test](http://todobackend.com/specs/index.html?https://todo-backend-sinatra.herokuapp.com/todos).

**Comment by moredip** [comment]
Thanks for reporting this. Looks like it's browser-specific; I don't see any errors in Chrome. Can you tell me which browser and version you are seeing this in?

**Comment by tuupola** [comment]
Chrome Version 52.0.2743.116 (64-bit) on OSX 10.10.5 (14F27). 

You are correct. Does not happen with Safari. So it probably goes away with next Chrome update.

**Comment by moredip** [comment]
It could also possibly be a chrome extension that you have installed which
is causing leaks. Could you try running the tests in an incognito tab?

**Comment by tuupola** [comment]
I tried disabling Privacy Badger and AdBlock but problem still existed. However problem disappeared when using incognito mode. So it is one of the extensions.

**Comment by moredip** [comment]
Good to know. Thanks for confirming that, and thanks again for reporting this.
